Add fullscreen export option
GDquest/GDquest-art-tools pull request #45
Opened 2020-06-13 22:41 UTC by johnbintz

**Please check if the PR fulfills these requirements:**

- [X] The commit message follows our guidelines.
- For bug fixes and features:
    - [X] You tested the changes.
    - [X] You updated the docs or changelog.

**What kind of change does this PR introduce?**

I needed fullscreen export for Synfig and mouth lipsync, since image imports in Synfig require a lot of manual tweaking that I wanted to avoid.

**Does this PR introduce a breaking change?**

Not as far as I know.

## New feature or change ##

**What is the current behavior?** 

All images are exported cropped to the layer's computed bounding box.

**What is the new behavior?**

A layer with `f=1` is exported to the size of the document's bounding box rather than the layer's.

**Other information**

2020-06-14 09:47 UTC, Larpon commented
This is also a good for working with individual animation frames that need to keep their size

2020-06-14 14:01 UTC, NathanLovato requested changes
Thanks. Rather than full screen, I'd like another keyword. This feature isn't exporting the screen but it suppresses trimming of layers in the document.

It could be t=false or t=0 for trim. Or something else.

I think the option is a bit limited and that ideally we'd be able to have export boxes/bounds custom for each layer. We've looked into that but couldn't do it efficiently with the API in the past.

In the meantime though, adding that feature is fine.

2020-06-14 16:20 UTC, johnbintz commented
Sounds good. I switched the options around to implement `t` instead, with the first possible setting being `false`.

2020-06-17 14:18 UTC, NathanLovato commented
Thanks!

2020-06-17 14:18 UTC, merged